### ISSUE TITLE
Update Readme.md

### ISSUE THREAD

**Issue by thomasverleye** [paulstraw/FancySelect#84]
Hello,

In the readme you explain that if you want to enable/disable selectboxes you'll have to do .trigger('enable.fs') or .trigger('disable.fs').
This doesn't work and after a while I found out the keywords were 'enable' and 'disable' without the '.fs'.

Could this be updated for other developers who start to use this plugin?

Great thanks,

Thomas

**Comment by paulstraw** [comment]
Hey @thomasverleye, thanks for the feedback. I'm not actively making changes to FancySelect right now, but am planning on a complete overhaul + `2.0.0` before too long.
