### ISSUE TITLE
OptGroups not supported

### ISSUE THREAD

**Issue by markdieselcore** [paulstraw/FancySelect#85]
It would be great to have the ability to use optgroups for our select lists. Currently they just don't show up at all.

**Comment by paulstraw** [comment]
Hey @markdieselcore, thanks for the feedback. I'm not actively making changes to FancySelect right now, but am planning on a complete overhaul + 2.0.0 before too long.

**Comment by ryangiglio** [comment]
+1 for this request!

**Comment by paulstraw** [comment]
Hey @markdieselcore and @ryangiglio, I am not officially supporting or maintaining FancySelect at this time. You can read a bit more about the rationale behind that [in the readme](https://github.com/paulstraw/FancySelect#notice-fancyselect-is-no-longer-actively-maintained).

**Comment by ryangiglio** [comment]
Makes sense. Thanks for letting us know!
