### ISSUE TITLE
Validation On Select Box

### ISSUE THREAD

**Issue by TheMilkman82** [paulstraw/FancySelect#86]
I'm want the select box to turn red when validation fails but if I apply a style to the box already rendered then another dropdown box is drawn above the box.

$('#title').attr('style', 'background: #BE4C54 !important;');

How can I apply a red background the dropdown after submit(function(e)?

**Comment by paulstraw** [comment]
Probably the best way to handle something like this would be to apply a class to the parent element above your select. Something like `.has-errors`, possibly. Then you can handle the actual style change in CSS e.g.:

``` css
.has-errors .fancy-select .trigger {
  background: #BE4C54;
}
```

Hope that helps!

**Comment by TheMilkman82** [comment]
Thanks for replying so quickly but it's not working.

I've added it to fancySelect.css then call the following line on submit but nothing happens

$('#title').addClass('has-errors');

div.fancy-select ul.options li {
	padding: 8px 12px;
	color: #2B8686;
	cursor: pointer;
	white-space: nowrap;

	transition: all 50ms ease-out;
	-webkit-transition: all 50ms ease-out;
	-moz-transition: all 50ms ease-out;
	-ms-transition: all 50ms ease-out;
	-o-transition: all 50ms ease-out;
}

div.fancy-select ul.options li.selected,
div.fancy-select ul.options li.selected.hover {
	color: #ffffff;
}

**.has-errors .fancy-select .trigger {
  background: #BE4C54 !important;
}
**

<div class="col-md-10 dropDown">
                                                                <select name="title" id="title" autocomplete="off" class="form-cus form-control" oninvalid="this.setCustomValidity('Please select a title.')" onchange="this.setCustomValidity('')" required>
                                                                    <option value="">Title</option>
                                                                    <option value="Mr">Mr</option>
                                                                    <option value="Mrs">Mrs</option>
                                                                    <option value="Miss">Miss</option>
                                                                    <option value="Ms">Ms</option>
                                                                    <option value="Dr">Dr</option>
                                                                    <option value="Sir">Sir</option>
                                                                    <option value="Dame">Dame</option>
                                                                    <option value="Lady">Lady</option>
                                                                    <option value="Lord">Lord</option>
                                                                    <option value="Professor">Professor</option>
                                                                    <option value="Reverend">Reverend</option>
                                                                    <option value="Not shown">Not shown</option>
                                                                </select>
                                                            </div>

**Comment by TheMilkman82** [comment]
<div class="col-md-10 dropDown">
                                                                <select name="title" id="title" autocomplete="off" class="form-cus form-control" oninvalid="this.setCustomValidity('Please select a title.')" onchange="this.setCustomValidity('')" required>
                                                                    <option value="">Title</option>
                                                                    <option value="Mr">Mr</option>
                                                                    <option value="Mrs">Mrs</option>
                                                                    <option value="Miss">Miss</option>
                                                                    <option value="Ms">Ms</option>
                                                                    <option value="Dr">Dr</option>
                                                                    <option value="Sir">Sir</option>
                                                                    <option value="Dame">Dame</option>
                                                                    <option value="Lady">Lady</option>
                                                                    <option value="Lord">Lord</option>
                                                                    <option value="Professor">Professor</option>
                                                                    <option value="Reverend">Reverend</option>
                                                                    <option value="Not shown">Not shown</option>
                                                                </select>
                                                            </div>

**Comment by TheMilkman82** [comment]
`<div class="col-md-10 dropDown">
                                                                <select name="title" id="title" autocomplete="off" class="form-cus form-control" oninvalid="this.setCustomValidity('Please select a title.')" onchange="this.setCustomValidity('')" required>
                                                                    <option value="">Title</option>
                                                                    <option value="Mr">Mr</option>
                                                                    <option value="Mrs">Mrs</option>
                                                                    <option value="Miss">Miss</option>
                                                                    <option value="Ms">Ms</option>
                                                                    <option value="Dr">Dr</option>
                                                                    <option value="Sir">Sir</option>
                                                                    <option value="Dame">Dame</option>
                                                                    <option value="Lady">Lady</option>
                                                                    <option value="Lord">Lord</option>
                                                                    <option value="Professor">Professor</option>
                                                                    <option value="Reverend">Reverend</option>
                                                                    <option value="Not shown">Not shown</option>
                                                                </select>
                                                            </div>`

**Comment by paulstraw** [comment]
I can't read this, please format your code properly with code blocks according to [GFM](https://guides.github.com/features/mastering-markdown/#GitHub-flavored-markdown) and I'll take a look.

**Comment by TheMilkman82** [comment]
fancySelect.css

`div.fancy-select ul.options li {
	padding: 8px 12px;
	color: #2B8686;
	cursor: pointer;
	white-space: nowrap;

	transition: all 50ms ease-out;
	-webkit-transition: all 50ms ease-out;
	-moz-transition: all 50ms ease-out;
	-ms-transition: all 50ms ease-out;
	-o-transition: all 50ms ease-out;
}

div.fancy-select ul.options li.selected,
div.fancy-select ul.options li.selected.hover {
	color: #ffffff;
}

div.has-errors .fancy-select .trigger {
  background: #BE4C54 !important;
}`

custom.js

`$('#title').addClass('has-errors');`

index.html

`<select name="title" id="title" autocomplete="off" class="form-cus form-control" oninvalid="this.setCustomValidity('Please select a title.')" onchange="this.setCustomValidity('')" required>
                                                                    <option value="">Title</option>
                                                                    <option value="Mr">Mr</option>
                                                                    <option value="Mrs">Mrs</option>
                                                                    <option value="Miss">Miss</option>
                                                                    <option value="Ms">Ms</option>
                                                                    <option value="Dr">Dr</option>
                                                                    <option value="Sir">Sir</option>
                                                                    <option value="Dame">Dame</option>
                                                                    <option value="Lady">Lady</option>
                                                                    <option value="Lord">Lord</option>
                                                                    <option value="Professor">Professor</option>
                                                                    <option value="Reverend">Reverend</option>
                                                                    <option value="Not shown">Not shown</option>
                                                                </select>`

**Comment by TheMilkman82** [comment]
I've managed to work around it, I used your answer but need to use a different Div.

Thanks!

**Comment by TheMilkman82** [comment]
The problem now is has-errors is applied to all .fance-select when I only want it added when I add attribute

`$('#title').addClass('has-errors');`

`.has-errors .fancy-select .trigger {
  background: #BE4C54;
}`

**Comment by paulstraw** [comment]
You should only be adding the `.has-errors` class when you actually encounter an error.

**Comment by TheMilkman82** [comment]
I do but the select seems to inherit by default so it's always there by default when I specify form-cus form-control.

`<select name="title" id="title" autocomplete="off" class="form-cus form-control" oninvalid="this.setCustomValidity('Please select a title.')" onchange="this.setCustomValidity('')" required>
                                                                    <option value="">Title</option>`

`.has-error .input-group .form-cus,
.input-group .trigger {
  background: #BE4C54 !important;
}`

`.input-group .form-cus,
.input-group .trigger {
  background: none !important;
  border-width: 2px !important;
  border-style: solid;
  border-color: #FFFFFF;
  border-radius: 50px !important;
  height: 39px;
  padding: 8px 15px;
  color: #FFFFFF !important;
  margin-top: 15px !important;
  text-align: left;
  transition: all 0.8s;
  -moz-transition: all 0.8s;
  -webkit-transition: all 0.8s;
  -o-transition: all 0.8s;
  opacity: .6;
}`

**Comment by paulstraw** [comment]
This is not an issue with FancySelect, so I'm going to need to close it. I or someone else would be happy to help you in the slashrocket.io Slack, though!

**Comment by TheMilkman82** [comment]
So you don't know the answer, no worries!
