### ISSUE TITLE
A way to select a value using jquery

### ISSUE THREAD

**Issue by simogeo** [paulstraw/FancySelect#87]
Hi, 

Nice project. Works well but I'd like to be able to set selected value from jQuery instruction. Is there an easy way ?

For a classic select I would do something like that : `$("select.s-theme").val("all");` but it does not work with fancySelect.

How can I achieve this. Thanks in advance.

**Comment by paulstraw** [comment]
Hey @simogeo, I am not officially supporting or maintaining FancySelect at this time. You can read a bit more about the rationale behind that [in the readme](https://github.com/paulstraw/FancySelect#notice-fancyselect-is-no-longer-actively-maintained).

**Comment by simogeo** [comment]
thanks for your reply.
