### ISSUE TITLE
close dropdown problem

### ISSUE THREAD

**Issue by rosivanov** [paulstraw/FancySelect#88]
1. open dropdown
2. click div.trigger several times to close dropdown. Sometimes dropdown is not closing espacially when clicking fast.  
Any browser, any platform.

Screencast https://drive.google.com/file/d/0B4gJaz6KIT-7dVdyNnQ2Mk1Zc1E/view

Any idea how to fix it?

**Comment by paulstraw** [comment]
Hey @rosivanov, I am not officially supporting or maintaining FancySelect at this time. You can read a bit more about the rationale behind that [in the readme](https://github.com/paulstraw/FancySelect#notice-fancyselect-is-no-longer-actively-maintained).
