### ISSUE TITLE
Add Bower and NPM Support

### ISSUE THREAD

**Issue by mike3run** [paulstraw/FancySelect#89]
Hello first of all thank you very much for this plugin i really love it I have used it around 2 times now but I always think that this would be much better for frontend developers to have it installable as a bower package or an npm package.

I'll leave some documentation to help you get started there: 
https://bower.io/docs/creating-packages/

I've published a bower package before is really easy I can help if you want me to but I think is best if the package is published under your name.

Cheers

**Comment by paulstraw** [comment]
Hey @mike3run, I am not officially supporting or maintaining FancySelect at this time.

**Comment by shelldandy** [comment]
Hey man no problem, can I then fork it and register it to bower/npm?

**Comment by paulstraw** [comment]
I'd rather you not, as I'm now recommending against its usage in general.
